# Using the ARM64 Debian Buster slim image as the base
FROM arm64v8/debian:buster-slim

# Install necessary packages for adding a new repository
RUN apt-get update && apt-get install -y wget gnupg software-properties-common \
    && wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - \
    && echo "deb https://packages.adoptium.net/artifactory/deb buster main" | tee /etc/apt/sources.list.d/adoptium.list \
    && apt-get update \
    && apt-get install -y temurin-17-jdk \
    && apt-get install -y --no-install-recommends \
        net-tools \
        curl \
        netcat \
        gnupg \
        wget \
        libsnappy-dev \
        tzdata \
    && rm -rf /var/lib/apt/lists/* # Clean up unnecessary files to reduce the image size

# Set JAVA_HOME environment variable, helpful for some applications
ENV JAVA_HOME /usr/lib/jvm/temurin-17-jdk-arm64

# Set PATH environment variable
ENV PATH $JAVA_HOME/bin:$PATH

# Verify installation
RUN java -version

# Install Kerberos client
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        krb5-user \
        libpam-krb5 \
        libpam-ccreds \
        krb5-config \
        krb5-pkinit \
    && rm -rf /var/lib/apt/lists/*
    
# Kerberos config
RUN mkdir -p etc/ssl/keytab
ENV KEYTAB_DIR=/etc/ssl/keytab

COPY krb5.conf /etc/krb5.conf
COPY jaas.conf /etc/jaas.conf

# Install multiple network diagnostic tools
RUN apt-get update && \
    apt-get install -y \
    iputils-ping \
    telnet \
    net-tools \
    traceroute \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce layer size

# Create the group 'supergroup'
RUN groupadd supergroup

# Add the 'root' user to the 'supergroup'
RUN usermod -a -G supergroup root
    
ENV TZ="Australia/Sydney"

COPY run.sh /app/run.sh
COPY target/hadoop-poc-1.0.0-SNAPSHOT.jar /app/hadoop-poc-1.0.0-SNAPSHOT.jar

RUN chmod +x /app/run.sh

# Kube probes
RUN touch /tmp/healthy
RUN echo "JGroups hl7 application is running" > /tmp/healthy

ENTRYPOINT ["/app/run.sh"]